name: GitHub Actions Demo

on: 
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubunto-latest
    steps:
      - run: |
          echo "Triggered event: ${{ github.event_name }}"
          echo "Branch triggered: ${{ github.ref }}"
      
      - uses: actions/checkout@v4.2.2
      - run: |
          echo "My repo '${{ github.repository }}' has this files:"
          tree
    
